package co.unicauca.sistemamedicion.microkernel.core.presentation;

import javax.swing.JOptionPane;
import co.unicauca.sistemamedicion.microkernel.common.entities.ItemMedicionElemento;
import co.unicauca.sistemamedicion.microkernel.common.entities.ProcesoElemento;
import co.unicauca.sistemamedicion.microkernel.core.business.ProcessService;
import co.unicauca.sistemamedicion.microkernel.core.business.ProductService;
import co.unicauca.sistemamedicion.microkernel.core.infra.Publisher;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Milthon Caicedo, Yazmin Gutierrez, Erica Camacho, Brandon Bohórquez, Juan Medicis
 */
public class GUIItemMedicion extends javax.swing.JInternalFrame {
    /**
     * Atributos 
     */
    private ProductService productService;
    private ProcessService processService;
    List<ItemMedicionElemento> productosIdeales;
    Publisher publisher;
    /**
     * Creates new form GUIItemMedicion
     */
    public GUIItemMedicion() {
        initComponents();
        productService = new ProductService();
        publisher = new Publisher();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jLabelAltura = new javax.swing.JLabel();
        jtxtAltura = new javax.swing.JTextField();
        jLabelAncho = new javax.swing.JLabel();
        jtxtAncho = new javax.swing.JTextField();
        jLabelPeso = new javax.swing.JLabel();
        jtxtPeso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelTipoProducto = new javax.swing.JLabel();
        jComboBoxTipoProducto = new javax.swing.JComboBox<>();
        jLabelCodigoProceso = new javax.swing.JLabel();
        jtxtCodigoProducto = new javax.swing.JTextField();
        jButtonEnviarMuestra = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jButtonCerrar = new javax.swing.JButton();

        jLabelAltura.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAltura.setText("ALTURA (CM)");

        jtxtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAlturaActionPerformed(evt);
            }
        });

        jLabelAncho.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAncho.setText("ANCHO (CM)");

        jtxtAncho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAnchoActionPerformed(evt);
            }
        });

        jLabelPeso.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelPeso.setText("PESO (KG)");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Datos del producto");

        jLabelTipoProducto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelTipoProducto.setText("TIPO DE PRODUCTO");

        jComboBoxTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cerveza", "Gaseosa" }));

        jLabelCodigoProceso.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelCodigoProceso.setText("CÓDIGO DE PRODUCTO");

        jButtonEnviarMuestra.setBackground(new java.awt.Color(54, 102, 167));
        jButtonEnviarMuestra.setText("Enviar muestra");
        jButtonEnviarMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarMuestraActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("NOMBRE O DESCRIPCIÓN DEL PRODUCTO");

        jButtonCerrar.setBackground(new java.awt.Color(194, 47, 47));
        jButtonCerrar.setText("Cerrar");

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonEnviarMuestra)
                                .addGap(285, 285, 285)
                                .addComponent(jButtonCerrar))
                            .addGroup(jPanelCentralLayout.createSequentialGroup()
                                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelAltura)
                                            .addComponent(jLabelAncho))
                                        .addGap(333, 333, 333)
                                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jtxtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                                            .addComponent(jtxtNombre)))
                                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jtxtAltura)
                                                .addComponent(jComboBoxTipoProducto, 0, 354, Short.MAX_VALUE))
                                            .addComponent(jLabelTipoProducto))
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelCodigoProceso)
                                            .addComponent(jtxtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtxtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoProducto)
                    .addComponent(jLabelCodigoProceso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAltura)
                    .addComponent(jLabelPeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCerrar)
                        .addContainerGap())
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEnviarMuestra)
                        .addContainerGap(38, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jtxtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAlturaActionPerformed

    private void jtxtAnchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAnchoActionPerformed
    }//GEN-LAST:event_jtxtAnchoActionPerformed
    /**
     * Accion para validar el tipo de proceso que se lleva a cabo 
     * @param evt 
     */
    private void jButtonEnviarMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarMuestraActionPerformed
        String tipoProducto = jComboBoxTipoProducto.getSelectedItem().toString();
        try {
            processService = new ProcessService();
            float Altura = Float.parseFloat(this.jtxtAltura.getText());
            float Ancho = Float.parseFloat(this.jtxtAncho.getText());
            float Peso = Float.parseFloat(this.jtxtPeso.getText());
            String nombre = this.jtxtNombre.getText();
            
            ItemMedicionElemento objItemMedicion = new ItemMedicionElemento();
            objItemMedicion.setAltura(Altura);
            objItemMedicion.setAncho(Ancho);
            objItemMedicion.setPeso(Peso);
            objItemMedicion.setNombre(nombre);
            objItemMedicion.setTipo(tipoProducto);
            ProcesoElemento ProcessEntity = new ProcesoElemento(objItemMedicion, this.jtxtCodigoProducto.getText());
            ProcesoElemento procesoRetornado = processService.ProcessProduct(ProcessEntity, Altura, Ancho, Peso);
            //Construyo el template de String y posteriormente enviar la información 
            String info = procesoRetornado.getElemento().getNombre()+ "," +
                    procesoRetornado.getElemento().getLstValoresReales().get(1)+ "," +
                    procesoRetornado.getElemento().getLstValoresReales().get(0)+ "," +
                    procesoRetornado.getElemento().getLstValoresReales().get(2)+ "," +
                    procesoRetornado.getElemento().getLstValoresIdeales().get(1)+ "," +
                    procesoRetornado.getElemento().getLstValoresIdeales().get(0)+ "," +
                    procesoRetornado.getElemento().getLstValoresIdeales().get(2)+ "," +
                    procesoRetornado.getElemento().getTipo()+ "," +
                    procesoRetornado.getElemento().getEstado();
            publisher.publish(info);
            
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Producto enviado con éxito", "Correcto", JOptionPane.INFORMATION_MESSAGE);
            
            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "No fue posible realizar el proceso al producto", "Error", JOptionPane.ERROR_MESSAGE);
            }   
    }//GEN-LAST:event_jButtonEnviarMuestraActionPerformed
    /**
     * Limpia los campos cuando se envía una medición correcta. 
     */
    private void limpiarCampos(){
        this.jtxtAltura.setText("");
        this.jtxtAncho.setText("");
        this.jtxtPeso.setText("");
        this.jtxtNombre.setText("");
        this.jtxtCodigoProducto.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonEnviarMuestra;
    private javax.swing.JComboBox<String> jComboBoxTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelAncho;
    private javax.swing.JLabel jLabelCodigoProceso;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelTipoProducto;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JTextField jtxtAltura;
    private javax.swing.JTextField jtxtAncho;
    private javax.swing.JTextField jtxtCodigoProducto;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPeso;
    // End of variables declaration//GEN-END:variables
}
