package co.unicauca.sistemamedicion.microkernel.core.presentation;

import co.unicauca.sistemamedicion.microkernel.common.entities.ItemMedicionElemento;
import co.unicauca.sistemamedicion.microkernel.common.entities.ProcesoElemento;
import co.unicauca.sistemamedicion.microkernel.core.business.ProcessService;
import co.unicauca.sistemamedicion.microkernel.core.business.ProductService;
import co.unicauca.sistemamedicion.microkernel.core.infra.Publisher;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author ahurtado
 */
public class GUISendProduct extends javax.swing.JFrame{
    
    private ProductService productService;
    private ProcessService processService;
    List<ItemMedicionElemento> products;
    Publisher publisher;
    /**
     * Creates new form GUISendProduct
     */
    public GUISendProduct() {
        initComponents();
        productService = new ProductService();
        publisher = new Publisher();
        loadProductIdeals();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxProducts = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIdProcess = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEstadoProducto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonProcesoProducto = new javax.swing.JButton();
        jButtonProductosOptimos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Envío de producto");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel2.setText("Seleccione el producto");
        jPanel1.add(jLabel2);

        jPanel1.add(jComboBoxProducts);

        jLabel4.setText("Indique codigo de proceso");
        jPanel1.add(jLabel4);

        jTextFieldIdProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdProcessActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldIdProcess);

        jLabel5.setText("Estado del producto");
        jPanel1.add(jLabel5);
        jPanel1.add(jTextFieldEstadoProducto);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButtonProcesoProducto.setText("Realizar Proceso al producto");
        jButtonProcesoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesoProductoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonProcesoProducto);

        jButtonProductosOptimos.setText("Realizar Envío a Productos Optimos");
        jButtonProductosOptimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductosOptimosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonProductosOptimos);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Carga los productos ideales con los respectivos datos ideales según los pluggins actuales
     */
    private void loadProductIdeals(){
        products = productService.getProductsIdeals();
        for (int index = 0; index < products.size(); index++) {
        jComboBoxProducts.addItem(products.get(index).getNombre());
        }
        jTextFieldEstadoProducto.setEnabled(false);
        jTextFieldEstadoProducto.setText("...");
        jButtonProductosOptimos.setVisible(false);
    }
    /**
     * Acción del botón que inicia el proceso que se le aplica al producto. 
     * @param evt 
     */
    private void jButtonProcesoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesoProductoActionPerformed

        ItemMedicionElemento selectedProduct = products.get(this.jComboBoxProducts.getSelectedIndex());
        ProcesoElemento ProcessEntity = new ProcesoElemento(selectedProduct, jTextFieldIdProcess.getText());
        try {
            processService = new ProcessService();
            ProcesoElemento procesoRetornado = processService.ProcessProduct(ProcessEntity, selectedProduct.getAltura(), 
                    selectedProduct.getAncho(),selectedProduct.getPeso());
            jTextFieldEstadoProducto.setText(""+procesoRetornado.getElemento().getEstado());
            jButtonProductosOptimos.setVisible(true);
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "No fue posible realizar el proceso al producto", "Error", JOptionPane.ERROR_MESSAGE);
        }

        
        
    }//GEN-LAST:event_jButtonProcesoProductoActionPerformed
    private void jButtonProductosOptimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductosOptimosActionPerformed
    }//GEN-LAST:event_jButtonProductosOptimosActionPerformed
    private void jTextFieldIdProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdProcessActionPerformed
    }//GEN-LAST:event_jTextFieldIdProcessActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonProcesoProducto;
    private javax.swing.JButton jButtonProductosOptimos;
    private javax.swing.JComboBox<String> jComboBoxProducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldEstadoProducto;
    private javax.swing.JTextField jTextFieldIdProcess;
    // End of variables declaration//GEN-END:variables

}
