/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.subscriber.processProducts.presentation;

import co.unicauca.sistemamedicion.microkernel.common.entities.ItemMedicionElemento;
import co.unicauca.subcriber.processProduct.service.ServiceProcessProduct;
import co.unicauca.subscriber.processProduct.model.Measurement;
import co.unicauca.subscriber.processProducts.infra.ISubscriber;
import co.unicauca.subscriber.processProducts.infra.RabbitListener;
import com.google.gson.Gson;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yavigutierrez
 */
public class DeliveryOffice extends javax.swing.JFrame implements ISubscriber {

    DefaultListModel modelList;
    /**
     * Creates new form DeliveryOffice
     */
    public DeliveryOffice() {
        initComponents();
        Runnable subscriber = new RabbitListener(this);
        //modelList = new DefaultListModel();
        //jList1.setModel(modelList);
        new Thread(subscriber).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPaneInfoDatosProductos = new javax.swing.JScrollPane();
        jTableInfoElementProcess = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableInfoElementProcess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Ancho Real(cm)", "Alto Real(cm)", "Peso Real(kg)", "Ancho Ideal(cm)", "Alto Ideal(cm)", "Peso Ideal(kg)", "Tipo", "Estado"
            }
        ));
        jScrollPaneInfoDatosProductos.setViewportView(jTableInfoElementProcess);

        jPanel1.add(jScrollPaneInfoDatosProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 810, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos Procesados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryOffice().setVisible(true);
            }
        });
    }
    
        @Override
    public void onMessage(String msg) {
        Gson gson = new Gson();
        //ItemMedicionElemento elemento = gson.fromJson(msg, ItemMedicionElemento.class);
        String auxMsg = msg.replaceAll(" ", ",");
//        Measurement objM = gson.fromJson(msg, Measurement.class);
//            System.out.println("auxMsg "+auxMsg);
       // Product product = gson.fromJson(msg, Product.class);
       /**
        * Guardo en la base de datos 
        */
       ServiceProcessProduct objService = new ServiceProcessProduct();
       
       Measurement objM = new Measurement();
       String partes1[] = auxMsg.split(",");
            for (int i = 0; i < partes1.length; i++) {
                System.out.println("v: "+ partes1[i]);
            }
        try {
            int response = 0;
            response = objService.addMeasurement(objM);
            if(response != 1){
                JOptionPane.showMessageDialog(this,"Error al insertar la medición a la db", "Insertar Medición", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DeliveryOffice.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        String[] partes = msg.split(" ");
            for (int i = 0; i < partes.length; i++) {
                System.out.println("es: "+partes[i]);
            }
        cargarTabla(partes);
        
        
    }
    
    public void cargarTabla(String [] partes){
        Object [] fila = new Object[9];
        fila[0]=partes[0];
        fila[1]=partes[1];
        fila[2]=partes[2];
        fila[3]=partes[3];
        fila[4]=partes[4];
        fila[5]=partes[5];
        fila[6]=partes[6];
        fila[7]=partes[7];
        fila[8]=partes[8];
        
        DefaultTableModel modelo =(DefaultTableModel) this.jTableInfoElementProcess.getModel(); 
        modelo.addRow(fila); 
        this.jTableInfoElementProcess.setModel(modelo);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneInfoDatosProductos;
    private javax.swing.JTable jTableInfoElementProcess;
    // End of variables declaration//GEN-END:variables


}
